spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  application:
    name: dashboard
  graphql:
    http:
      path: /graphql
    websocket:
      path: /graphql
      connection-init-timeout: 60s
    graphiql:
      enabled: true
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: GET, POST
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true