spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql   # 추가! 명시적으로 경로 지정
  application:
    name: dashboard
  graphql:
    http:
      path: /graphql
    websocket:
      path: /graphql
      connection-init-timeout: 60s
    graphiql:
      enabled: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1   # 추가! 앱 종료 전까지 DB 유지
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true        # 추가! JPA 초기화 후 schema.sql 실행
  cors: # 추가!
    allowed-origins: "http://localhost:5173"  # Vite 기본 포트
    allowed-methods: GET, POST